### PR TITLE
SCP Transfer

### PR DESCRIPTION
**Pull request by ian-cameron**
Implements SFTP / SCP transfer using SSH.NET library as suggested in Issue #99 and in the Wiki article by @ChesireFreeThrow. Also added a bit to ControllerTypes to opt-in to this functionality.

### CODE REVIEW

**Comment by udotdevelopment** [comment]
It would be nice to see this reference the Controller ID rather than having to add an SFTP column in the database so it doesn't get bloated

**Comment by udotdevelopment** [comment]
No, in the EF migration you add a column to the DB. To select if a controller type does SFTP or not. I think it would be cleaner and less bloat on the DB to just do it based on controller type. The new .net core logger we are making injects the protocol based on controller type. no need to add an additional DB column

**Comment by ian-cameron** [comment]
How are you able to "just do it based on controller type?" Is it hard-coded / not configurable?  Based on Description or ControllerTypeID or something else?  Maybe if I could see this new branch I'd understand.

**Comment by ian-cameron** [comment]
Thanks! I'll leave it open for others to compare and in the mean time we have to roll with it for a client deployment.  I will share any lessons learned if we have any issues in production.  

If someone wants to use this without adding a column, however, the second to last commit of this PR: https://github.com/udotdevelopment/ATSPM/pull/124/commits/4f06259d3f79acbc07608350f16560b39e01265 is doing it based on magic string in the existing FTPDirectory column ^sftp://.  (I'm okay to add a column to our DB because EF won't care unless there's a naming conflict)

The new logger with 5.0 sounds great and will solve all of this!

**Comment by ian-cameron** [comment]
Going to close this now.  In production this didn't work for our use case.  The firmware version on our controllers only supported SCP, no SFTP commands.  The SSH.NET library didn't have SCP download with wildcard (it required a known filename) so instead of working around all that I used the WinSCP .Net assembly, which supported wildcards and delete after download.  Very smooth and working well.  For anyone interested:  https://github.com/kittelson/ATSPM/tree/winscp-transfer

**Pull request closed without merging**
